import{a as m}from"./assets/vendor-B2YOV0tR.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const a={headerBurger:document.querySelector("[data-menu-open]"),modalHeaderCloseBtn:document.querySelector(".close-menu-btn"),modalHeader:document.querySelector("[data-menu]"),logoLinkMenu:document.querySelector(".logo-link"),mobileNavLinks:document.querySelector(".mobile-nav-links"),artistsListElm:document.querySelector("[data-artist-gallery]"),loadMoreBtnElm:document.querySelector("[data-btn-load-more]"),artistLoaderElm:document.querySelector("[data-artist-loader]"),artistInfoElm:document.querySelector("[data-artist-info]"),artistsModalBackdrop:document.querySelector("[data-artists-modal]"),artistsModalCloseBtn:document.querySelector(".artists-modal-close-btn"),artistModalLoaderElm:document.querySelector("[data-artist-detail-loader]"),feedbackSliderPrevBtn:document.querySelector(".swiper-button-prev"),feedbackSliderNextBtn:document.querySelector(".swiper-button-next"),feedbackSliderPagination:document.querySelector(".swiper-pagination"),openFeedbackBtn:document.querySelector(".leave-feedback-btn"),feedbackLoaderElm:document.querySelector("[data-feedback-loader]"),feedbackSliderWrapperElm:document.querySelector("[data-feedbackLists]"),feedbackFormBackdrop:document.querySelector("[data-feedback-form]"),feedbackFormEL:document.querySelector(".form-main"),feedbackFormCloseBtn:document.querySelector(".form-main-btn"),feedbackFormRatingContainer:document.querySelector(".form-str"),feedbackFormSubmitBtn:document.querySelector(".form-end-button"),body:document.body};function b(t){const{_id:r,strArtist:s,strArtistThumb:n,genres:e=[],strBiographyEN:o}=t,i='<ul class="artists-genres-list">'+e.map(y=>`<li class="artists-genre-item">${y}</li>`).join(" ")+"</ul>",p=o?o.slice(0,60)+"...":"No description available.";return`
    <li class="artists-card">
      <img src="${n}" alt="${s}" class="artist-photo" />
      ${i}
      <h4 class="artists-name epilogue">${s}</h4>
      <p class="artists-description">${p}</p>
      <button class="learn-more-btn" data-id="${r}" type="button">
        <span class="learn-more-text">Learn More</span>
        <svg class="learn-more-icon" viewBox="0 0 31 32" width="24" height="24">
          <use href="/img/icons.svg#icon-right-caret-learn-more"></use>
        </svg>
      </button>
    </li>
  `}function L(t){const r=t.map(b).join("");a.artistsListElm.insertAdjacentHTML("beforeend",r)}function g(){a.loadMoreBtnElm.classList.remove("visually-hidden")}function d(){a.loadMoreBtnElm.classList.add("visually-hidden")}function h(){a.artistLoaderElm.classList.remove("visually-hidden")}function S(){a.artistLoaderElm.classList.add("visually-hidden")}m.defaults.baseURL="https://sound-wave.b.goit.study/api";async function q(t=1,r=8){const s="/artists",n={limit:r,page:t};return(await m.get(s,{params:n})).data}function k(t){console.log(`ArtistID: ${t}`)}let c=1;const l=8;let u;f();async function f(){try{d(),h();const t=await q(c,l),r=t.artists,s=t.totalArtists;L(r),u=Math.ceil(s/l),c<u?(g(),c++):d()}catch(t){a.artistsListElm.innerHTML=`Помилка завантаження артистів: ${t}`}S()}function v(){f()}a.loadMoreBtnElm.addEventListener("click",v);a.artistsListElm.addEventListener("click",t=>{const r=t.target.closest(".learn-more-btn");if(!r)return;const s=r.dataset.id;if(!s){console.warn('Не знайдено data-id на кнопці "Learn More"');return}k(s)});
//# sourceMappingURL=index.js.map
